# frozen_string_literal: true

require 'fileutils'
require 'optparse'

module SubmodulerParent
  class InstallCommand
    def initialize(args)
      @args = args
      @options = {}
      parse_options
    end

    def execute
      install_bin_files
      0
    rescue StandardError => e
      puts "Error during installation: #{e.message}"
      1
    end

    private

    def parse_options
      OptionParser.new do |opts|
        opts.banner = "Usage: submoduler_parent install [options]"
        opts.on("-h", "--help", "Show this help") do
          puts opts
          exit 0
        end
        opts.on("-f", "--force", "Force overwrite existing files") do
          @options[:force] = true
        end
      end.parse!(@args)
    end

    def install_bin_files
      host_bin_dir = File.expand_path('../../bin', find_project_root)
      vendor_bin_dir = File.expand_path('../../../bin', __dir__)

      puts "Installing submoduler_parent bin files..."
      puts "  Source: #{vendor_bin_dir}"
      puts "  Target: #{host_bin_dir}"

      # Ensure host bin directory exists
      FileUtils.mkdir_p(host_bin_dir)

      # Install submoduler_parent.rb
      install_submoduler_parent_script(host_bin_dir, vendor_bin_dir)
      
      # Install or update submoduler wrapper
      install_submoduler_wrapper(host_bin_dir)

      puts "✓ Installation complete!"
    end

    def install_submoduler_parent_script(host_bin_dir, vendor_bin_dir)
      target_file = File.join(host_bin_dir, 'submoduler_parent.rb')
      
      if File.exist?(target_file) && !@options[:force]
        puts "  ✓ submoduler_parent.rb already exists (use --force to overwrite)"
        return
      end

      script_content = generate_submoduler_parent_script
      File.write(target_file, script_content)
      FileUtils.chmod(0755, target_file)
      
      puts "  ✓ Created bin/submoduler_parent.rb"
    end

    def install_submoduler_wrapper(host_bin_dir)
      target_file = File.join(host_bin_dir, 'submoduler')
      
      if File.exist?(target_file) && !@options[:force]
        puts "  ✓ submoduler wrapper already exists (use --force to overwrite)"
        return
      end

      wrapper_content = generate_submoduler_wrapper_script
      File.write(target_file, wrapper_content)
      FileUtils.chmod(0755, target_file)
      
      puts "  ✓ Created bin/submoduler wrapper"
    end

    def generate_submoduler_parent_script
      <<~RUBY
        #!/usr/bin/env ruby
        # frozen_string_literal: true
        
        # Auto-generated by submoduler_parent install command
        # This script provides direct access to submoduler_parent functionality
        
        # Get the project root directory
        project_root = File.expand_path('..', __dir__)
        
        # Add the submoduler_parent lib directory to load path
        $LOAD_PATH.unshift File.join(project_root, 'vendor', 'submoduler_parent', 'lib')
        
        require 'submoduler_parent'
        
        # Run CLI and exit with returned code
        exit SubmodulerParent::CLI.run(ARGV)
      RUBY
    end

    def generate_submoduler_wrapper_script
      <<~RUBY
        #!/usr/bin/env ruby
        # frozen_string_literal: true
        
        # Auto-generated by submoduler_parent install command
        # Wrapper script that calls submoduler_parent.rb
        
        require 'pathname'
        
        # Get the project root directory
        project_root = Pathname.new(__FILE__).dirname.parent
        
        # Path to the submoduler_parent script
        submoduler_script = project_root.join('bin', 'submoduler_parent.rb')
        
        unless submoduler_script.exist?
          puts "Error: Submoduler script not found at \#{submoduler_script}"
          puts "Run 'ruby vendor/submoduler_parent/bin/submoduler_parent.rb install' to install bin files"
          exit 1
        end
        
        # Execute the submoduler script with all arguments
        exec('ruby', submoduler_script.to_s, *ARGV)
      RUBY
    end

    def find_project_root
      SubmodulerCommon::SubmodulerIni.find_project_root
    rescue SubmodulerCommon::SubmodulerIni::NotFoundError => e
      raise e.message
    end
  end
end